import { 
    Apple, 
    Banana, 
    ChickenBreast, 
    Bread,
    Carrots,
    Chips,
    Chocolate,
    Cucumber,
    Eggs,
    IceCream,
    Juice,
    Letuce,
    Milk,
    Pasta,
    Rice,
    Salmon,
    Susages,
    Tomato,
    Beef,
    Yogurt
} from "@/public/Icons"

 export const productImages = {
    "Apple": Apple,
    "Banana": Banana,
    "Chicken Breast": ChickenBreast,
    "Salmon": Salmon,
    "Bread": Bread,
    "Milk": Milk,
    "Eggs": Eggs,
    "Tomato": Tomato,
    "Cucumber": Cucumber,
    "Chocolate Bar": Chocolate,
    "Pasta": Pasta,
    "Lettuce": Letuce,
    "Orange Juice": Juice,
    "Potato Chips": Chips,
    "Ground Beef": Beef, 
    "Rice": Rice,
    "Yogurt": Yogurt,
    "Carrots": Carrots,
    "Ice Cream": IceCream,
    "Sausages": Susages
}
